server:
  port: 1234

spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/db4tt
      username: db4tt
      password: c4Nrwa6e2cKH6eLJ