spring:
  profiles:
    active: dev

mybatis-plus:
  global-config:
    db-config:
      id-type: auto
---
server:
  port: 80

spring:
  profiles: dev
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/toutiao
      username: root
      password: 123456
---
server:
  port: 80

spring:
  profiles: pro
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/toutiao
      username: root
      password: 123456
---
server:
  port: 80

spring:
  profiles: test
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/toutiao
      username: root
      password: 123456